/**
 * GradeConcernRepository.java
 * Purpose: Grade concern database operations.
 * Organization note: Executable code and original formatting below are unchanged.
 */

package studentmanagement;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public final class GradeConcernRepository {

    private GradeConcernRepository() {
    }

    /**
     * Creates a concern for a student with a released grade.
     *
     * @return The ConcernID generated by MySQL.
     */
    public static int submitConcern(
            String studentNumber,
            String subjectCode,
            String reason) throws SQLException {

        if (studentNumber == null || studentNumber.trim().isEmpty()
                || subjectCode == null || subjectCode.trim().isEmpty()
                || reason == null || reason.trim().isEmpty()) {
            throw new IllegalArgumentException(
                    "Student, subject and reason are required.");
        }

        String findGrade =
                "SELECT g.GradeID, g.SubmissionStatus, "
              + "s.SubjectID, s.TeacherID "
              + "FROM Users u "
              + "JOIN Subjects s ON s.SubjectCode = ? "
              + "JOIN Grades g ON g.StudentID = u.UserID "
              + "AND g.SubjectID = s.SubjectID "
              + "WHERE u.StudentNumber = ? "
              + "FOR UPDATE";

        String findActiveConcern =
                "SELECT ConcernID FROM Grade_Concerns "
              + "WHERE StudentID = ? AND SubjectID = ? "
              + "AND Status IN ('Pending', 'Under Review') "
              + "LIMIT 1";

        String insertConcern =
                "INSERT INTO Grade_Concerns "
              + "(StudentID, SubjectID, TeacherID, ConcernText) "
              + "VALUES (?, ?, ?, ?)";

        String findStudent =
                "SELECT UserID FROM Users "
              + "WHERE StudentNumber = ? AND Role = 'Student'";

        try (Connection connection =
                     DatabaseConnection.getConnection()) {

            connection.setAutoCommit(false);

            try {
                int studentId;

                try (PreparedStatement statement =
                             connection.prepareStatement(findStudent)) {

                    statement.setString(1, studentNumber.trim());

                    try (ResultSet results = statement.executeQuery()) {
                        if (!results.next()) {
                            throw new IllegalArgumentException(
                                    "Student not found.");
                        }

                        studentId = results.getInt("UserID");
                    }
                }

                int subjectId;
                int teacherId;

                // Lock the student's grade while checking eligibility.
                try (PreparedStatement statement =
                             connection.prepareStatement(findGrade)) {

                    statement.setString(1, subjectCode.trim());
                    statement.setString(2, studentNumber.trim());

                    try (ResultSet results = statement.executeQuery()) {
                        if (!results.next()) {
                            throw new IllegalStateException(
                                    "No grade record exists for this student "
                                  + "and subject.");
                        }

                        String status =
                                results.getString("SubmissionStatus");

                        if (!"Posted".equals(status)) {
                            throw new IllegalStateException(
                                    "The grade must be posted by the Registrar first.");
                        }

                        subjectId = results.getInt("SubjectID");
                        teacherId = results.getInt("TeacherID");

                        if (results.wasNull()) {
                            throw new IllegalStateException(
                                    "This subject has no assigned teacher.");
                        }
                    }
                }

                try (PreparedStatement statement =
                             connection.prepareStatement(findActiveConcern)) {

                    statement.setInt(1, studentId);
                    statement.setInt(2, subjectId);

                    try (ResultSet results = statement.executeQuery()) {
                        if (results.next()) {
                            throw new IllegalStateException(
                                    "An active concern already exists "
                                  + "for this subject.");
                        }
                    }
                }

                int concernId;

                try (PreparedStatement statement =
                             connection.prepareStatement(
                                     insertConcern,
                                     Statement.RETURN_GENERATED_KEYS)) {

                    statement.setInt(1, studentId);
                    statement.setInt(2, subjectId);
                    statement.setInt(3, teacherId);
                    statement.setString(4, reason.trim());

                    if (statement.executeUpdate() != 1) {
                        throw new SQLException(
                                "Concern insertion was unsuccessful.");
                    }

                    try (ResultSet keys =
                                 statement.getGeneratedKeys()) {

                        if (!keys.next()) {
                            throw new SQLException(
                                    "MySQL did not return a concern ID.");
                        }

                        concernId = keys.getInt(1);
                    }
                }

                connection.commit();
                return concernId;

            } catch (SQLException | RuntimeException exception) {
                connection.rollback();
                throw exception;

            } finally {
                connection.setAutoCommit(true);
            }
        }
    }

public static java.util.List<GradeConcern> loadStudentConcerns(
        String studentNumber) throws SQLException {

    java.util.List<GradeConcern> concerns =
            new java.util.ArrayList<>();

    String sql =
            "SELECT gc.ConcernID, gc.ConcernText, gc.Status, "
          + "s.SubjectCode "
          + "FROM Grade_Concerns gc "
          + "JOIN Users u ON gc.StudentID = u.UserID "
          + "JOIN Subjects s ON gc.SubjectID = s.SubjectID "
          + "WHERE u.StudentNumber = ? "
          + "ORDER BY gc.DateRaised DESC, gc.ConcernID DESC";

    try (Connection connection =
                 DatabaseConnection.getConnection();
         PreparedStatement statement =
                 connection.prepareStatement(sql)) {

        statement.setString(1, studentNumber);

        try (ResultSet results = statement.executeQuery()) {

            Student student = null;

            for (Student candidate : AcademicData.getStudents()) {
                if (candidate.getStudentNumber()
                        .equals(studentNumber)) {
                    student = candidate;
                    break;
                }
            }

            if (student == null) {
                throw new IllegalArgumentException(
                        "Student not found in AcademicData.");
            }

            while (results.next()) {

                String subjectCode =
                        results.getString("SubjectCode");

                Course course = null;

                for (Course candidate : AcademicData.getCourses()) {
                    if (candidate.getCourseCode()
                            .equals(subjectCode)) {
                        course = candidate;
                        break;
                    }
                }

                if (course == null) {
                    throw new IllegalStateException(
                            "Course not found: " + subjectCode);
                }

                GradeConcern concern = new GradeConcern(
                        results.getInt("ConcernID"),
                        student,
                        course,
                        results.getString("ConcernText")
                );

                concern.setStatus(
                        results.getString("Status"));

                concerns.add(concern);
            }
        }
    }

    return concerns;
}


public static java.util.List<GradeConcern> loadAllConcerns()
        throws SQLException {

    java.util.List<GradeConcern> concerns =
            new java.util.ArrayList<>();

    String sql =
            "SELECT gc.ConcernID, gc.ConcernText, gc.Status, "
          + "u.StudentNumber, s.SubjectCode "
          + "FROM Grade_Concerns gc "
          + "JOIN Users u ON gc.StudentID = u.UserID "
          + "JOIN Subjects s ON gc.SubjectID = s.SubjectID "
          + "ORDER BY gc.DateRaised DESC, gc.ConcernID DESC";

    try (Connection connection =
                 DatabaseConnection.getConnection();
         PreparedStatement statement =
                 connection.prepareStatement(sql);
         ResultSet results = statement.executeQuery()) {

        while (results.next()) {

            String studentNumber =
                    results.getString("StudentNumber");

            String subjectCode =
                    results.getString("SubjectCode");

            Student student = null;
            Course course = null;

            for (Student candidate : AcademicData.getStudents()) {
                if (candidate.getStudentNumber()
                        .equals(studentNumber)) {
                    student = candidate;
                    break;
                }
            }

            for (Course candidate : AcademicData.getCourses()) {
                if (candidate.getCourseCode()
                        .equals(subjectCode)) {
                    course = candidate;
                    break;
                }
            }

            if (student == null || course == null) {
                throw new IllegalStateException(
                        "Cannot match concern "
                        + results.getInt("ConcernID")
                        + " to its student or course.");
            }

            GradeConcern concern = new GradeConcern(
                    results.getInt("ConcernID"),
                    student,
                    course,
                    results.getString("ConcernText")
            );

            concern.setStatus(results.getString("Status"));
            concerns.add(concern);
        }
    }

    return concerns;
}


public static void markUnderReview(int concernId)
        throws SQLException {

    if (concernId <= 0) {
        throw new IllegalArgumentException(
                "A valid concern ID is required.");
    }

    String sql =
            "UPDATE Grade_Concerns "
          + "SET Status = 'Under Review' "
          + "WHERE ConcernID = ? "
          + "AND Status = 'Pending'";

    try (Connection connection =
                 DatabaseConnection.getConnection();
         PreparedStatement statement =
                 connection.prepareStatement(sql)) {

        statement.setInt(1, concernId);

        int updated = statement.executeUpdate();

        if (updated != 1) {
            throw new IllegalStateException(
                    "Concern not found or no longer Pending. "
                  + "Refresh the concern list.");
        }
    }
}

}
